/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyecto.vistas;

import java.awt.Color;
import java.awt.Point;
import java.awt.event.ItemEvent;

import java.time.ZoneId;
import java.time.ZoneOffset;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.tools.DocumentationTool.Location;
import proyecto.conexion.ClienteData;
import proyecto.conexion.MascotaData;
import proyecto.entidades.Cliente;
import proyecto.entidades.Mascota;


/**
 *
 * @author benja
 */
public class MascotaVistas extends javax.swing.JInternalFrame {
    int codigoMascotaActual;

    /** Creates new form Mascota */
    public MascotaVistas() {
        initComponents();
        cargarCombo();
        jPanel2.setVisible(false);
        jPanel4.setVisible(false);
    }
public void cargarCombo (){
    ClienteData cd = new ClienteData();
    List<Cliente> clienteslista = cd.ClientesTodos();
    for(Cliente cliente:clienteslista){
        JCBSeleccionDuenio.addItem(cliente);
    }
}
public void cargarComboM (int id){
    
    MascotaData md = new MascotaData();
    List<Mascota> mascotaslista = md.obtenerMascotas(id);
    
    for(Mascota mascota: mascotaslista){
        JCBSeleccionMascota.addItem(mascota);
        
    }
    
}
public void borrarComboM(){
    JCBSeleccionMascota.removeAllItems();
}
public void limpiarComboM(int idCliente){
        int cant;
        cant= JCBSeleccionMascota.getItemCount();
        for(int i=0; i<= cant; i++){
            if (((Mascota)JCBSeleccionMascota.getItemAt(i)).getIdCliente()!=idCliente){
                JCBSeleccionMascota.removeItem(JCBSeleccionMascota.getItemAt(i));
            }
        }
}
public void llenarTextos(Mascota mascota){
    if(mascota != null){
        
    Date date = Date.from(mascota.getFechaNacimiento().atStartOfDay(ZoneId.systemDefault()).toInstant());
    JTFNombre.setText(mascota.getAlias());
    JTFColor.setText(mascota.getColorPelo());
    JTFEspecie.setText(mascota.getEspecie());
    JTFRaza.setText(mascota.getRaza());
    JTFPeso.setText(Double.toString(mascota.getPeso()));
    JTFSexo.setText(mascota.getSexo());
    JDCFecha.setDate(date);
    
    
        
    }else{
    JTFNombre.setText("");
    JTFColor.setText("");
    JTFEspecie.setText("");
    JTFRaza.setText("");
    JTFPeso.setText("");
    JTFSexo.setText("");
    JDCFecha.setDate(null);
        
    }
    }
public Mascota mascotaActual(){
    MascotaData md = new MascotaData();
    Mascota mascota = md.buscarMascota(codigoMascotaActual);
    
    return mascota;
}
float [] hsbColor1 = Color.RGBtoHSB(237, 215, 138, null);

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JCBSeleccionDuenio = new javax.swing.JComboBox<>();
        JCBSeleccionMascota = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JBNuevaMascota = new javax.swing.JButton();
        JBModificarMascota = new javax.swing.JButton();
        JBEliminarMascota = new javax.swing.JButton();
        JTFNombre = new javax.swing.JTextField();
        JTFEspecie = new javax.swing.JTextField();
        JTFPesoM = new javax.swing.JTextField();
        JTFRaza = new javax.swing.JTextField();
        JTFColor = new javax.swing.JTextField();
        JTFPeso = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        JTFSexo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        JBGuardar2 = new javax.swing.JButton();
        JBCancelar2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        JBGuardarN = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        JDCFecha = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("\t\t\tMASCOTA");
        setPreferredSize(new java.awt.Dimension(760, 492));
        setRequestFocusEnabled(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.setPreferredSize(new java.awt.Dimension(720, 480));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("SELECCIONE DUEÑO:");
        BackGround.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setText("SELECCIONE MASCOTA:");
        BackGround.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        JCBSeleccionDuenio.setEnabled(false);
        JCBSeleccionDuenio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCBSeleccionDuenioItemStateChanged(evt);
            }
        });
        BackGround.add(JCBSeleccionDuenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, -1));

        JCBSeleccionMascota.setEnabled(false);
        JCBSeleccionMascota.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCBSeleccionMascotaItemStateChanged(evt);
            }
        });
        BackGround.add(JCBSeleccionMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 210, -1));

        jLabel4.setText("DATOS MASCOTA:");
        BackGround.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jPanel1.setBackground(new java.awt.Color(238, 189, 138));

        JBNuevaMascota.setBackground(new java.awt.Color(237, 215, 138));
        JBNuevaMascota.setText("NUEVA MASCOTA");
        JBNuevaMascota.setBorder(null);
        JBNuevaMascota.setBorderPainted(false);
        JBNuevaMascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBNuevaMascotaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBNuevaMascotaMouseEntered(evt);
            }
        });
        JBNuevaMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNuevaMascotaActionPerformed(evt);
            }
        });

        JBModificarMascota.setBackground(new java.awt.Color(237, 215, 138));
        JBModificarMascota.setText("MODIFICAR MASCOTA");
        JBModificarMascota.setBorder(null);
        JBModificarMascota.setBorderPainted(false);
        JBModificarMascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBModificarMascotaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBModificarMascotaMouseEntered(evt);
            }
        });
        JBModificarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBModificarMascotaActionPerformed(evt);
            }
        });

        JBEliminarMascota.setBackground(new java.awt.Color(237, 215, 138));
        JBEliminarMascota.setText("ELIMINAR MASCOTA");
        JBEliminarMascota.setBorder(null);
        JBEliminarMascota.setBorderPainted(false);
        JBEliminarMascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBEliminarMascotaMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBEliminarMascotaMouseEntered(evt);
            }
        });
        JBEliminarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEliminarMascotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JBModificarMascota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBNuevaMascota, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(JBEliminarMascota, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(JBNuevaMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBModificarMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBEliminarMascota, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        BackGround.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 200, 130));

        JTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNombreActionPerformed(evt);
            }
        });
        BackGround.add(JTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 90, -1));

        JTFEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFEspecieActionPerformed(evt);
            }
        });
        BackGround.add(JTFEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 90, -1));
        BackGround.add(JTFPesoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 90, -1));
        BackGround.add(JTFRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 90, -1));

        JTFColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFColorActionPerformed(evt);
            }
        });
        BackGround.add(JTFColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 90, -1));
        BackGround.add(JTFPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 90, 20));

        jPanel3.setBackground(new java.awt.Color(238, 189, 138));

        jLabel16.setText("NOMBRE:");

        jLabel17.setText("ESPECIE:");

        jLabel5.setText("RAZA:");

        jLabel6.setText("COLOR:");

        jLabel7.setText("PESO:");

        jLabel8.setText("PESO M:");

        jLabel9.setText("SEXO:");

        jLabel10.setText("FECHA");

        jLabel11.setText("NAC:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BackGround.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 260));
        BackGround.add(JTFSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 90, -1));

        jPanel4.setBackground(new java.awt.Color(238, 189, 138));

        JBGuardar2.setBackground(new java.awt.Color(237, 215, 138));
        JBGuardar2.setText("GUARDAR");
        JBGuardar2.setBorder(null);
        JBGuardar2.setBorderPainted(false);
        JBGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGuardar2ActionPerformed(evt);
            }
        });

        JBCancelar2.setBackground(new java.awt.Color(237, 215, 138));
        JBCancelar2.setText("CANCELAR");
        JBCancelar2.setBorder(null);
        JBCancelar2.setBorderPainted(false);
        JBCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBGuardar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBCancelar2, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBGuardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBCancelar2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        BackGround.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 150, 80));

        jPanel2.setBackground(new java.awt.Color(238, 189, 138));

        JBGuardarN.setBackground(new java.awt.Color(237, 215, 138));
        JBGuardarN.setText("GUARDAR");
        JBGuardarN.setBorder(null);
        JBGuardarN.setBorderPainted(false);
        JBGuardarN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBGuardarNMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBGuardarNMouseEntered(evt);
            }
        });
        JBGuardarN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGuardarNActionPerformed(evt);
            }
        });

        JBCancelar.setBackground(new java.awt.Color(237, 215, 138));
        JBCancelar.setText("CANCELAR");
        JBCancelar.setBorder(null);
        JBCancelar.setBorderPainted(false);
        JBCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBCancelarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBCancelarMouseEntered(evt);
            }
        });
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBGuardarN, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBGuardarN, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BackGround.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 150, 90));
        BackGround.add(JDCFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 90, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/iconos/Colorful Cute Cats Illustration Desktop Wallpaper.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        BackGround.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 460));

        getContentPane().add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 758, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBNuevaMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNuevaMascotaActionPerformed
       Point location =JBNuevaMascota.getLocation();
       JCBSeleccionDuenio.setEnabled(true);
       JBNuevaMascota.setEnabled(false);
       jPanel2.setVisible(true);

       
    }//GEN-LAST:event_JBNuevaMascotaActionPerformed

    
    
    private void JTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNombreActionPerformed

    private void JTFEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFEspecieActionPerformed

    private void JTFColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFColorActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
       jPanel2.setVisible(false);
       JBNuevaMascota.setEnabled(true);
       JCBSeleccionDuenio.setEnabled(false);
       JCBSeleccionMascota.setEnabled(false);
      
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JBGuardarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGuardarNActionPerformed
       Cliente clienteSelect = (Cliente) (JCBSeleccionDuenio.getSelectedItem());
       Mascota mascotaNueva = new Mascota();
       mascotaNueva.setIdCliente(clienteSelect.getIdCliente());
       mascotaNueva.setAlias(JTFNombre.getText());
       mascotaNueva.setEspecie(JTFEspecie.getText());
       mascotaNueva.setRaza(JTFRaza.getText());
       mascotaNueva.setPeso(Double.parseDouble(JTFPeso.getText()));
       mascotaNueva.setPesoMedio(Double.parseDouble(JTFPeso.getText()));
       mascotaNueva.setColorPelo(JTFColor.getText());
       mascotaNueva.setSexo(JTFSexo.getText());
       
       mascotaNueva.setFechaNacimiento(JDCFecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
       MascotaData md = new MascotaData();
       md.guardarMascota(mascotaNueva);
      jPanel2.setVisible(false);
       JBNuevaMascota.setEnabled(true);
       JCBSeleccionDuenio.setEnabled(false);
       JCBSeleccionMascota.setEnabled(false);
       
    }//GEN-LAST:event_JBGuardarNActionPerformed

    private void JBNuevaMascotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBNuevaMascotaMouseEntered
        
        JBNuevaMascota.setBackground(Color.getHSBColor(21, 42, 93));
    }//GEN-LAST:event_JBNuevaMascotaMouseEntered

    private void JBNuevaMascotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBNuevaMascotaMouseExited
        JBNuevaMascota.setBackground(Color.getHSBColor(hsbColor1[0],hsbColor1[1],hsbColor1[2]));
    }//GEN-LAST:event_JBNuevaMascotaMouseExited

    private void JBModificarMascotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBModificarMascotaMouseEntered
        JBModificarMascota.setBackground(Color.getHSBColor(21, 42, 93));
    }//GEN-LAST:event_JBModificarMascotaMouseEntered

    private void JBModificarMascotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBModificarMascotaMouseExited
        JBModificarMascota.setBackground(Color.getHSBColor(hsbColor1[0],hsbColor1[1],hsbColor1[2]));
    }//GEN-LAST:event_JBModificarMascotaMouseExited

    private void JBEliminarMascotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBEliminarMascotaMouseEntered
        JBEliminarMascota.setBackground(Color.getHSBColor(21, 42, 93));
    }//GEN-LAST:event_JBEliminarMascotaMouseEntered

    private void JBEliminarMascotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBEliminarMascotaMouseExited
       JBEliminarMascota.setBackground(Color.getHSBColor(hsbColor1[0],hsbColor1[1],hsbColor1[2]));
    }//GEN-LAST:event_JBEliminarMascotaMouseExited

    private void JBGuardarNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBGuardarNMouseEntered
        JBGuardarN.setBackground(Color.getHSBColor(21, 42, 93));
    }//GEN-LAST:event_JBGuardarNMouseEntered

    private void JBGuardarNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBGuardarNMouseExited
       JBGuardarN.setBackground(Color.getHSBColor(hsbColor1[0],hsbColor1[1],hsbColor1[2]));
    }//GEN-LAST:event_JBGuardarNMouseExited

    private void JBCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBCancelarMouseEntered
       JBCancelar.setBackground(Color.getHSBColor(21, 42, 93));
    }//GEN-LAST:event_JBCancelarMouseEntered

    private void JBCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBCancelarMouseExited
      JBCancelar.setBackground(Color.getHSBColor(hsbColor1[0],hsbColor1[1],hsbColor1[2]));
    }//GEN-LAST:event_JBCancelarMouseExited

    private void JBEliminarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEliminarMascotaActionPerformed
     Mascota mascota = new Mascota();
     MascotaData md = new MascotaData();
     mascota = (Mascota) JCBSeleccionMascota.getSelectedItem();
     md.borrarMascota(mascota.getCodigo());
    }//GEN-LAST:event_JBEliminarMascotaActionPerformed

    private void JBModificarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBModificarMascotaActionPerformed
        jPanel4.setVisible(true);
        JBModificarMascota.setEnabled(false);
        JCBSeleccionDuenio.setEnabled(true);
        JCBSeleccionMascota.setEnabled(true);
        JTFPesoM.setEnabled(false);
    }//GEN-LAST:event_JBModificarMascotaActionPerformed

    private void JBGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGuardar2ActionPerformed
        
        Mascota mascota = new Mascota();
        MascotaData md = new MascotaData();
        mascota = md.buscarMascota(codigoMascotaActual);
        System.out.println(mascota.getAlias());
        mascota.setAlias(JTFNombre.getText());
        mascota.setSexo(JTFSexo.getText());
        mascota.setEspecie(JTFEspecie.getText());
        mascota.setRaza(JTFRaza.getText());
        mascota.setColorPelo(JTFColor.getText());
        mascota.setFechaNacimiento(JDCFecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        mascota.setPesoMedio(mascotaActual().getPesoMedio());
        mascota.setPeso(Integer.parseInt(JTFPeso.getText()));
        mascota.setIdCliente(mascotaActual().getIdCliente());
        mascota.setCodigo(mascotaActual().getCodigo());
        md.modificarMascota(mascota);
        
        
    }//GEN-LAST:event_JBGuardar2ActionPerformed

    private void JBCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelar2ActionPerformed
        JBModificarMascota.setEnabled(true);
        jPanel4.setVisible(false);
         JCBSeleccionDuenio.setEnabled(false);
        JCBSeleccionMascota.setEnabled(false);
    }//GEN-LAST:event_JBCancelar2ActionPerformed

    private void JCBSeleccionDuenioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCBSeleccionDuenioItemStateChanged
if(evt.getStateChange() == ItemEvent.SELECTED){
   Cliente clienteSelect = (Cliente) JCBSeleccionDuenio.getSelectedItem();
   JCBSeleccionMascota.removeAllItems();
    cargarComboM(clienteSelect.getIdCliente());
}
if(evt.getStateChange() == ItemEvent.DESELECTED){
    Cliente clienteSelect= null;
    JCBSeleccionMascota.removeAllItems();
}       

        
      
    }//GEN-LAST:event_JCBSeleccionDuenioItemStateChanged

    private void JCBSeleccionMascotaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCBSeleccionMascotaItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
              llenarTextos((Mascota)JCBSeleccionMascota.getSelectedItem());
          codigoMascotaActual=((Mascota)JCBSeleccionMascota.getSelectedItem()).getCodigo();
        }  
        
          
    }//GEN-LAST:event_JCBSeleccionMascotaItemStateChanged
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBCancelar2;
    private javax.swing.JButton JBEliminarMascota;
    private javax.swing.JButton JBGuardar2;
    private javax.swing.JButton JBGuardarN;
    private javax.swing.JButton JBModificarMascota;
    private javax.swing.JButton JBNuevaMascota;
    private javax.swing.JComboBox<Cliente> JCBSeleccionDuenio;
    private javax.swing.JComboBox<Mascota> JCBSeleccionMascota;
    private com.toedter.calendar.JDateChooser JDCFecha;
    private javax.swing.JTextField JTFColor;
    private javax.swing.JTextField JTFEspecie;
    private javax.swing.JTextField JTFNombre;
    private javax.swing.JTextField JTFPeso;
    private javax.swing.JTextField JTFPesoM;
    private javax.swing.JTextField JTFRaza;
    private javax.swing.JTextField JTFSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

}
