/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyecto.vistas;

import java.sql.Date;
import javax.swing.JOptionPane;
import proyecto.conexion.VisitaData;
import proyecto.entidades.Cliente;
import proyecto.entidades.Visita;
import java.time.LocalDate;
import proyecto.conexion.ClienteData;
import proyecto.conexion.MascotaData;
import proyecto.entidades.Mascota;
import proyecto.entidades.Tratamiento;
import proyecto.vistas.MenuVeterinaria;

/**
 *
 * @author piry
 */
public class VisitaVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form VisitaVista
     */
    public VisitaVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        codigoTratamiento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        codigoMascota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        sintomas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pesoPromedio = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        buscarTratamiento = new javax.swing.JButton();
        buscarMascota = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("Codigo de Tratamiento:");

        jLabel2.setText("Codigo de Mascota:");

        jLabel3.setText("Fecha:");

        jLabel4.setText("Sintomas:");

        jLabel5.setText("Peso Promedio: ");

        guardar.setText("GUARDAR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        eliminar.setText("ELIMINAR");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        buscarTratamiento.setText("BUSCAR");
        buscarTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTratamientoActionPerformed(evt);
            }
        });

        buscarMascota.setText("BUSCAR");
        buscarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMascotaActionPerformed(evt);
            }
        });

        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(codigoTratamiento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(codigoMascota, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(fecha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(sintomas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(pesoPromedio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(guardar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(eliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(buscarTratamiento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(buscarMascota, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(guardar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoTratamiento)
                    .addComponent(codigoMascota)
                    .addComponent(sintomas)
                    .addComponent(pesoPromedio, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                        .addComponent(eliminar)
                        .addGap(61, 61, 61)))
                .addGap(18, 18, 18)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscarTratamiento)
                    .addComponent(buscarMascota))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigoTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarTratamiento))
                .addGap(18, 18, 18)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codigoMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarMascota))
                .addGap(20, 20, 20)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sintomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pesoPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar)
                    .addComponent(eliminar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        Visita visita = new Visita();
        ClienteData clienteData = new ClienteData();
        VisitaData visitaData = new VisitaData();
        MascotaData mascotaData = new MascotaData();
        Mascota mascota = new Mascota();
        Cliente cliente = new Cliente();
        visita.setCodigoTratamiento(Integer.parseInt(codigoTratamiento.getText()));
        visita.setCodigoMascota(Integer.parseInt(codigoMascota.getText()));
        visita.setFecha((Date) fecha.getDate());
        visita.setSintomas(sintomas.getText());
        visita.setPesoPromedio(Integer.parseInt(pesoPromedio.getText()));
        mascota = mascotaData.buscarMascota(Integer.parseInt(codigoMascota.getText()));
        
        if(clienteData.buscarClientePorId(mascota.getIdCliente()) == null){
            visitaData.guardarVisita(visita);
        }else{
            cliente = clienteData.buscarClientePorId(mascota.getIdCliente());
            JOptionPane.showMessageDialog(null, "El cliente ya existe, elige su tratamiento");
            escritorio.removeAll();
            escritorio.repaint();
            MascotasDelClienteVista mc = new MascotasDelClienteVista(cliente);
            mc.setVisible(true);
            escritorio.add(mc);
            escritorio.moveToFront(mc);
            
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        VisitaData visitaData = new VisitaData();
        String input = JOptionPane.showInputDialog("Por favor, ingrese el idVisita entero:");
        int numero;
        try {
            numero = Integer.parseInt(input);
            visitaData.eliminarVisita(numero);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Entrada no válida. Ingrese un número entero.");
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void buscarTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTratamientoActionPerformed
        // TODO add your handling code here:
        
        ListaDeTratamientosVista lt = new ListaDeTratamientosVista();
        lt.setVisible(true);
        MenuVeterinaria.obtenerEscritorio().add(lt);
        Tratamiento tratamiento1 = lt.obtenerTratamiento();
        codigoTratamiento.setText(tratamiento1.getCodigo()+"");
        //escritorio.add(lt);
        //escritorio.moveToFront(lt);
        
        
    }//GEN-LAST:event_buscarTratamientoActionPerformed

    private void buscarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMascotaActionPerformed
        // TODO add your handling code here:
        MascotasDelClienteVista mc = new MascotasDelClienteVista();
        Mascota mascota1 = mc.obtenerMascota();
        codigoMascota.setText(mascota1.getCodigo()+"");
    }//GEN-LAST:event_buscarMascotaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarMascota;
    private javax.swing.JButton buscarTratamiento;
    private javax.swing.JTextField codigoMascota;
    private javax.swing.JTextField codigoTratamiento;
    private javax.swing.JButton eliminar;
    private javax.swing.JDesktopPane escritorio;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField pesoPromedio;
    private javax.swing.JTextField sintomas;
    // End of variables declaration//GEN-END:variables
}
